spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://43.143.171.43:5432/postgres
    username: postgres
    password: postgres_terakoya

server:
  port: 9999
  servlet:
    context-path: /api